sudo: required

language: node_js

node_js:
  - '6'

script:
  - yarn run ci

before_deploy:
  - sudo apt-get update -qq
  - sudo apt-get install --yes python-pip
  - sudo pip install git+https://github.com/hatch-sh/hatch.git@master

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master

cache: yarn

notifications:
  email: false
